export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const FETCH_PRODUCTS_DONE = "FETCH_PRODUCTS_DONE";
export const FETCH_PRODUCTS_ERRROR = "FETCH_PRODUCTS_ERROR";

export const LOADING_BALANCE = "LOADING_BALANCE";
export const FETCH_CURRENT_BALANCE = "FETCH_CURRENT_BALANCE";
export const FETCH_BALANCE_ERROR = "FETCH_BALANCE_ERROR";

export const INCREMENTING_BALANCE = "INCREMENTING_BALANCE";
export const INCREMENT_BALANCE_DONE = "INCREMENT_BALANCE_DONE";
export const INCREMENT_BALANCE_ERROR = "INCREMENT_BALANCE_ERROR";

export const DECREMENTING_BALANCE = "DECREMENTING_BALANCE";
export const DECREMENT_BALANCE_DONE = "DECREMENT_BALANCE_DONE";
export const DECREMENTING_BALANCE_ERROR = "DECREMENTING_BALANCE_ERROR";

export const BUYING_PRODUCT = "BUYING_PRODUCT";
export const BUY_PRODUCT_DONE = "BUY_PRODUCT_DONE";
export const BUY_PRODUCT_ERROR = "BUY_PRODUCT_ERROR";

export const RETURNING_PRODUCT = "RETURNING_PRODUCT";
export const PRODUCT_RETURNED = "PRODUCT_RETURNED";
export const RETURNING_PRODUCT_ERROR = "RETURNING_PRODUCT_ERROR";

export const PRODUCT_RETURN = "PRODUCT_RETURN";
export const FETCH_PURCHASED_PRODUCTS = "FETCH_PURCHASED_PRODUCTS";
